### PR TITLE
New Sorting Algorithms

### PR DESCRIPTION
**Pull request by fungamer2-2**

### CODE REVIEW

**Comment by gaming32** [comment]
Good work! I will merge it after I add Quick Sandpaper Sort to Run All. Please remind me if I forget.

**Comment by gaming32** [comment]
Should I accept the pull request, or are you going to make more changes? @fungamer2-2

**Comment by fungamer2-2** [comment]
Sure, I think that's all I have for now.

**Comment by gaming32** [comment]
Ok 👍

**Pull request merged**
