### PR TITLE
Ciura Cocktail Shell Sort

### PR DESCRIPTION
**Pull request by fungamer2-2**

### CODE REVIEW

**Comment by Gaming32** [comment]
A semicolon needs to be added to make this compile.

**Comment by fungamer2-2** [comment]
Fixed

**Comment by yg8ijvjvjv** [comment]
Stop it with Gaming32. Use the modern Array Visualizer at https://github.com/yg8ijvjvjv/ModernArrayVisualizer .

**Comment by yg8ijvjvjv** [comment]
Stop it with MusicTheorist and Gaming32. We have the modern Array Visualizer in https://github.com/yg8ijvjvjv/ModernArrayVisualizer, which is the latest version of Array Visualizer.

**Comment by MusicTheorist** [comment]
@yg8ijvjvjv I'm getting sick and tired of this, Piotr. Either stop spamming our repo or we will ban you.

**Pull request merged**
